
const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCH CHATS"

const NEW_ATTACHMENTS = "NEW_ATTACHMENTS"
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"
const NEW_MESSAGE = "NEW_MESSAGE"

const NEW_REQUEST = "NEW_REQUEST"

const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEFT = "CHAT_LEFT"

const ONLINE_USER = "ONLINE_USER"


export { ALERT, REFETCH_CHATS, NEW_ATTACHMENTS, NEW_MESSAGE_ALERT, NEW_REQUEST, NEW_MESSAGE, STOP_TYPING, START_TYPING, CHAT_JOINED, CHAT_LEFT,ONLINE_USER }